apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo
  namespace: devlopment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-demo
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      containers:
      - image: leizenan/jenkins-demo:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: jenkins-demo
        env:
        - name: branch
          value: <BRANCH_NAME>
---
apiVersion: v1
kind: Service
metadata:
   name: demo
   namespace: devlopment
spec:
   selector:
     app: jenkins-demo
   type: ClusterIP
   ports:
   - port: 18888
     targetPort: 18888
     #nodePort: 31889
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
  namespace: devlopment
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: deploy.lucky.com
    http:
      paths:
      - path: /
        pathType:  Prefix
        backend:
         service:
           name: demo
           port:
            number: 18888
